account_settings/urls.py
# coding: utf-8
from django.conf.urls import include, url
from account_settings import views

urlpatterns = [
    url(r'^$', views.settings, name='settings'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^emails/$', views.emails, name='emails'),
    url(r'^picture/$', views.picture, name='picture'),
    url(r'^password/$', views.password, name='password'),
    
    url(r'^upload_picture/$', views.upload_picture, name='upload_picture'),
    url(r'^save_uploaded_picture/$', views.save_uploaded_picture, name='save_uploaded_picture'),
]

authentication/urls.py
from django.conf.urls import url
from authentication import views

app_name = "authentication"

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.reset_confirm, name='password_reset_confirm'),
    url(r'^success/$', views.success, name='success'),





]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from landing import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    
    url(r'^landing/',include('landing.urls',namespace='landing')),
    url(r'',include('authentication.urls',namespace='authentication')),
    url(r'^settings/', include('account_settings.urls', namespace='settings')),

]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from landing import views

urlpatterns = [
       url(r'^admin/', include(admin.site.urls)),
       url(r'^$',views.IndexView.as_view()),
       
       url(r'^landing/',include('landing.urls',namespace='landing')),
       url(r'',include('authentication.urls',namespace='authentication')),
       url(r'^settings/', include('account_settings.urls', namespace='settings')),
]

templates/includes/footer.html
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-6 legal">
        <span>© XpressMania.</span>
      </div>
      <div class="col-xs-6 social">
        <a href="https://github.com" target="_blank" data-toggle="tooltip" title="Github" data-placement="top"><span class="fa fa-github"></span></a>
        <a href="https://twitter.com" target="_blank" data-toggle="tooltip" title="Twitter" data-placement="top"><span class="fa fa-twitter"></span></a>
        <a href="https://youtube.com" target="_blank" data-toggle="tooltip" title="Youtube" data-placement="top"><span class="fa fa-youtube"></span></a>
        <a href="https://plus.google.com" target="_blank" data-toggle="tooltip" title="Google+" data-placement="top"><span class="fa fa-google-plus"></span></a>
      </div>
    </div>
  </div>
</footer>

templates/includes/header.html
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button data-target="#header-menu" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand value-brand">XpressMania</a>
      </div>
      <div class="collapse navbar-collapse" id="header-menu">
        <ul class="nav navbar-nav">
          <li><a href="#">Blog</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Help</a></li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="#">
                <span data-toggle="tooltip" data-placement="bottom" data-container="body" title="My profile">{{ user.profile.get_screen_name }}</span>
              </a>
            </li>
            <li>
              <span class="navbar-text username-divider"></span>
            </li>

            <li>
              <a href="{% url 'settings:settings' %}">
                <span data-toggle="tooltip" data-placement="bottom" data-container="body" title="Account settings">
                  <span class="glyphicon glyphicon-cog"></span>
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'authentication:signout' %}">
                <span data-toggle="tooltip" data-placement="bottom" data-container="body" title="Sign out">
                  <span class="glyphicon glyphicon-log-out"></span>
                </span>
              </a>
            </li>
          </ul>
        {% else %}
          <a href="{% url 'authentication:signin' %}" title="Sign in" class="btn btn-default navbar-btn navbar-right">Sign in</a>
          <a href="{% url 'authentication:signup' %}" title="Sign up" class="btn btn-primary navbar-btn navbar-right" style="margin-right: 5px;">Sign up</a>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

templates/includes/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible fade in {% if message.tags %}{% if message.tags == 'error' %}alert-danger{% elif message.tags == 'debug' %}alert-warning{% else %}alert-{{ message.tags }}{% endif %}{% else %}alert-info{% endif %}" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}