landing/urls.py
from django.conf.urls import url
from landing import views

app_name = "landing"

urlpatterns = [
    url(r'^$',views.DistributorsListView.as_view(),name='list'),
    url(r'^(?P<pk>\d)/$',views.DistributorsDetailView.as_view(),name ='detail'),
    url(r'^create/$', views.DistributorsCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d)/$',views.DistributorsUpdateView.as_view(),name ='update'),
    url(r'^delete/(?P<pk>\d)/$',views.DistributorsDeleteView.as_view(),name ='delete'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from landing import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    
    url(r'^landing/',include('landing.urls',namespace='landing')),
    url(r'',include('authentication.urls',namespace='authentication')),
    url(r'^settings/', include('account_settings.urls', namespace='settings')),

]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from landing import views

urlpatterns = [
       url(r'^admin/', include(admin.site.urls)),
       url(r'^$',views.IndexView.as_view()),
       
       url(r'^landing/',include('landing.urls',namespace='landing')),
       url(r'',include('authentication.urls',namespace='authentication')),
       url(r'^settings/', include('account_settings.urls', namespace='settings')),
]

landing/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Distributors(models.Model):
    name = models.CharField(max_length = 256)
    address = models.CharField(max_length = 256)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("landing:detail",kwargs = {'pk':self.pk})


class Shop(models.Model):
    name = models.CharField(max_length = 256)
    address = models.CharField(max_length = 256)
    latitude = models.FloatField()
    longitude = models.FloatField()
    distributor = models.ForeignKey(Distributors,related_name='shop')

    def __str__(self):
        return self.name

landing/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from landing.models import Distributors,Shop
from django.core.urlresolvers import reverse_lazy

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class DistributorsListView(ListView):
    context_object_name = 'distributors'
    model = Distributors

class DistributorsDetailView(DetailView):
    context_object_name = 'distributors_detail'
    model = Distributors
    template_name = "landing/distributors_detail.html"

class DistributorsCreateView(CreateView):
    fields = ('name','address','latitude','longitude')
    model = Distributors

class DistributorsUpdateView(UpdateView):
    fields = ('name','address','latitude','longitude')
    model = Distributors

class DistributorsDeleteView(DeleteView):
    model = Distributors
    success_url = reverse_lazy("landing:list")

landing/templates/landing/distributors_confirm_delete.html
{% extends "landing/landing_base.html" %}
{% block body_block %}
  <h1>Delete {{distributors.name}}?</h1>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'landing:detail' pk=distributors.pk %}">Cancel</a>

  </form>
{% endblock %}

landing/templates/landing/distributors_detail.html
{% extends "landing/landing_base.html" %}
{% block body_block %}


  <div class="jambotron">
    <h1>WElcome to Distributors Detail list!!</h1>
    <h2>Distributors Name</h2>
    <p>Name: {{distributors_detail.name}}</p>
    <p>address: {{distributors_detail.address}}</p>
    <p>Latitude: {{distributors_detail.latitude}}</p>
    <p>Longitude: {{distributors_detail.longitude}}</p>

    <h3>List of Shops</h2>
    {% for shop in distributors_detail.shop.all %}
      <p>{{shop.name}} is located at address {{shop.address}} {{shop.latitude}} {{shop.longitude}}</p>
    {% endfor %}
  </div>

  <div class="container">
    <p><a class="btn btn-warning" href="{% url 'landing:update' pk=distributors_detail.pk %}">Update</a></p>
  </div>


{% endblock %}

landing/templates/landing/distributors_form.html
{% extends "landing/landing_base.html" %}
{% block body_block %}

    <h1>
      {% if not form.instance.pk %}
      Create Distributors
      {% else %}
      Update Distributors
      {% endif %}
    </h1>


    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>

{% endblock %}

landing/templates/landing/distributors_list.html
{% extends "landing/landing_base.html" %}
{% block body_block %}

  <h1>Welcome to Distributors list!!</h1>
  <ol>
    {% for distributor in distributors %}
    <h2><li><a href="{{distributor.id}}">{{distributor.name}}</a></li></h2>
    {% endfor %}
  </ol>

{% endblock %}

landing/templates/landing/landing_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/selectize.bootstrap3.css' %}" rel="stylesheet">
    <link href="{% static 'css/parsifal.css' %}?v=2" rel="stylesheet">
  </head>
  <body>
    {% include 'includes/footer.html' %}
    <nav class = "navbar navbar-default navbar-static-top " >
      <ol class="nav navbar-nav" >
        <li><a class="navbar-brand" href="#">Distributors</a></li>
        <li><a class="navbar-link" href="#">Shop</a></li>
        <li></li>
      </ol>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock%}
    </div>
  </body>
</html>