account_settings/urls.py
# coding: utf-8
from django.conf.urls import include, url
from account_settings import views

urlpatterns = [
    url(r'^$', views.settings, name='settings'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^emails/$', views.emails, name='emails'),
    url(r'^picture/$', views.picture, name='picture'),
    url(r'^password/$', views.password, name='password'),
    
    url(r'^upload_picture/$', views.upload_picture, name='upload_picture'),
    url(r'^save_uploaded_picture/$', views.save_uploaded_picture, name='save_uploaded_picture'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from landing import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    
    url(r'^landing/',include('landing.urls',namespace='landing')),
    url(r'',include('authentication.urls',namespace='authentication')),
    url(r'^settings/', include('account_settings.urls', namespace='settings')),

]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from landing import views

urlpatterns = [
       url(r'^admin/', include(admin.site.urls)),
       url(r'^$',views.IndexView.as_view()),
       
       url(r'^landing/',include('landing.urls',namespace='landing')),
       url(r'',include('authentication.urls',namespace='authentication')),
       url(r'^settings/', include('account_settings.urls', namespace='settings')),
]

account_settings/models.py
from django.db import models

# Create your models here.

account_settings/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm

from authentication.models import Profile

class UserEmailForm(forms.ModelForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={ 'class': 'form-control' }),
            max_length=254,
            help_text='This email account will not be publicly available. It is used for your Parsifal account management, such as internal notifications and password reset.')

    class Meta:
        model = User
        fields = ['email',]


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'form-control' }), max_length=30, required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'form-control' }), max_length=30, required=False)
    public_email = forms.CharField(widget=forms.EmailInput(attrs={ 'class': 'form-control' }), max_length=254, required=False)

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        try:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
        except User.DoesNotExist:
            pass

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name']

    def save(self, *args, **kwargs):
        u = self.instance.user
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.save()
        profile = super(ProfileForm, self).save(*args,**kwargs)
        return profile

class PasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={ 'class': 'form-control' }))
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={ 'class': 'form-control' }))
    new_password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={ 'class': 'form-control' }))

account_settings/views.py
# coding: utf-8

import os


from oauthlib.oauth2 import TokenExpiredError


from django.core.urlresolvers import reverse as r
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden
from django.contrib import messages
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404, render
from django.conf import settings as django_settings
from django.contrib.auth import update_session_auth_hash

from account_settings.forms import UserEmailForm, ProfileForm, PasswordForm


@login_required
def settings(request):
    return redirect('/settings/profile/')

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, u'Your profile were successfully edited.')
            return redirect(r('settings:profile'))
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'settings/profile.html', { 'form': form })

@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET['upload_picture'] == 'uploaded':
            uploaded_picture = True
    except Exception:
        uploaded_picture = False
    return render(request, 'settings/picture.html', { 'uploaded_picture': uploaded_picture })

@login_required
def emails(request):
    if request.method == 'POST':
        form = UserEmailForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, u'Account Email changed successfully.')
        else:
            messages.error(request, u'Please correct the error below.')
    else:
        form = UserEmailForm(instance=request.user)
    return render(request, 'settings/emails.html', { 'form' : form })

@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, u'Password changed successfully.')
            update_session_auth_hash(request, form.user)
        else:
            messages.error(request, u'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'settings/password.html', { 'form' : form })


@login_required
def upload_picture(request):
    try:
        f = request.FILES['picture']
        ext = os.path.splitext(f.name)[1].lower()
        valid_extensions = ['.gif', '.png', '.jpg', '.jpeg', '.bmp']
        if ext in valid_extensions:
            filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
            with open(filename, 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
            im = Image.open(filename)
            width, height = im.size
            if width > 560:
                new_width = 560
                new_height = (height * 560) / width
                new_size = new_width, new_height
                im.thumbnail(new_size, Image.ANTIALIAS)
                im.save(filename)
            return redirect('/settings/picture/?upload_picture=uploaded')
        else:
            messages.error(request, u'Invalid file format.')
    except Exception:
        messages.error(request, u'An expected error occurred.')
    return redirect('/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST['x'])
        y = int(request.POST['y'])
        w = int(request.POST['w'])
        h = int(request.POST['h'])
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' + request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)
        return HttpResponse(django_settings.MEDIA_URL + 'profile_pictures/' + request.user.username + '.jpg')
    except Exception:
        return HttpResponseBadRequest()

account_settings/templates/settings/connections.html
{% extends 'base.html' %}

{% block title %}Account Settings · Xpressmania{% endblock %}

{% block javascript %}
  <script>
    $(function () {

      $.fn.loadConnection = function (url) {
        var url = $(this).attr("data-remote");
        var container = $(this);
        $.ajax({
          url: url,
          cache: false,
          beforeSend: function () {
            $(container).spinner(false);
            $(".block-spinner", container).addClass("pull-right");
          },
          success: function (data) {
            $(container).html(data);
          },
          complete: function () {
            $(container).spinner();
          }
        });
      };


    });
  </script>
{% endblock javascript %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Connected Services</h3>
        </div>
        <ul class="list-group">
          <li class="list-group-item">

          </li>
          <li class="list-group-item">
            
          </li>
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}

account_settings/templates/settings/emails.html
{% extends 'base.html' %}

{% block title %}Account Settings · XpressMania{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form action="{% url 'settings:emails' %}" method="post">
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Account email</h3>
          </div>
          <div class="panel-body">
            {% include 'form_vertical.html' with form=form %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-success btn-large">Save email</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

account_settings/templates/settings/password.html
{% extends 'base.html' %}

{% block title %}Account Settings · XpressMania{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form method="post">
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Change password</h3>
          </div>
          <div class="panel-body">
            {% include 'form_vertical.html' with form=form %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-success">Change password</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

account_settings/templates/settings/picture.html
{% extends 'base.html' %}

{% block title %}Account Settings · XpressMania{% endblock %}

{% load staticfiles %}

{% block stylesheet %}
  <link href="{% static 'css/jquery.Jcrop.min.css' %}" rel="stylesheet">
  <style>
    .jcrop-keymgr {
      display: none!important;
    }
  </style>
{% endblock stylesheet %}

{% block javascript %}
  <script type="text/javascript" src="{% static 'js/jquery.Jcrop.min.js' %}?_=1"></script>
  <script type="text/javascript" src="{% static 'js/profile.js' %}?_=1"></script>
  <script>
    {% if uploaded_picture %}
      $(function () {
        $("#modal-upload-picture").modal('show');
        window.history.pushState("", "", "/settings/picture/");
      });
    {% endif %}
  </script>
{% endblock javascript %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form enctype="multipart/form-data" method="post" action="{% url 'settings:upload_picture' %}" id="picture-upload-form" class="form-block">
        {% csrf_token %}
        <input type="file" name="picture" class="hide">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Profile picture</h3>
          </div>
          <div class="panel-body">
            <img src="{{ user.profile.get_picture }}" style="width: 200px;" class="thumbnail profile-picture">
          </div>
          <div class="panel-footer">
            <button type="button" class="btn btn-primary" id="btn-upload-picture">Upload new picture</button>
          </div>
        </div>

        <div class="modal fade" id="modal-upload-picture">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Crop Profile Picture</h4>
              </div>
              <div class="modal-body">
                {% if uploaded_picture %}
                  <div class="selected-picture">
                    <p>Crop the profile picture and then click on the <strong>Save Picture</strong> button</p>
                    <img src="{{ MEDIA_URL }}/profile_pictures/{{ request.user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                    <input type="hidden" id="x" name="x">
                    <input type="hidden" id="y" name="y">
                    <input type="hidden" id="w" name="w">
                    <input type="hidden" id="h" name="h">
                  </div>
                {% endif %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success btn-save-picture">Save picture</button>
              </div>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
{% endblock content %}

account_settings/templates/settings/profile.html
{% extends 'base.html' %}

{% block title %}Account Settings · XpressMania{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      {% include "settings/settings_menu.html" %}
    </div>
    <div class="col-md-9">
      <form action="{% url 'settings:profile' %}" method="post">
        {% csrf_token %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Edit Profile ({{ user.username }})</h3>
          </div>
          <div class="panel-body">
            {% include 'form_vertical.html' with form=form %}
          </div>
          <div class="panel-footer">
            <button type="submit" class="btn btn-success btn-large">Save profile</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

account_settings/templates/settings/settings_menu.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Account settings</h3>
  </div>
  <div class="list-group">
    <a href="{% url 'settings:profile' %}" class="list-group-item">Profile</a>
    <a href="{% url 'settings:emails' %}" class="list-group-item">Emails</a>
    <a href="{% url 'settings:picture' %}" class="list-group-item">Picture</a>
    <a href="{% url 'settings:password' %}" class="list-group-item">Password</a>
    {% comment %}<a href="{% url 'settings:connections' %}" class="list-group-item">Connected services</a>{% endcomment %}
  </div>
</div>